# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='dioder.proto',
  package='',
  serialized_pb='\n\x0c\x64ioder.proto\"1\n\x05\x43olor\x12\x0b\n\x03red\x18\x01 \x02(\r\x12\r\n\x05green\x18\x02 \x02(\r\x12\x0c\n\x04\x62lue\x18\x03 \x02(\r')




_COLOR = descriptor.Descriptor(
  name='Color',
  full_name='Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='red', full_name='Color.red', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='green', full_name='Color.green', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blue', full_name='Color.blue', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['Color'] = _COLOR

class Color(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COLOR
  
  # @@protoc_insertion_point(class_scope:Color)

# @@protoc_insertion_point(module_scope)
